let candidates = [
  { id: 1, name: "Rylee", email: "massa.Mauris@ornare.ca", address: "Ap #426-8143 Ligula. Ave", age: 62, companyId: 7, available: true },
  { id: 2, name: "Karen", email: "ante.Vivamus@nulla.co.uk", address: "475-4583 Nullam Ave", age: 40, companyId: 4, available: true },
  { id: 3, name: "Hiram", email: "nulla.at@odio.edu", address: "362-9928 Facilisi. Street", age: 69, companyId: 7, available: false },
  { id: 4, name: "John", email: "Suspendisse.eleifend@acfermentumvel.org", address: "197-8543 Malesuada Road", age: 49, companyId: 6, available: false },
  { id: 5, name: "Astra", email: "Nullam@tellus.org", address: "P.O. Box 204, 4435 Nulla Rd.", age: 43, companyId: 4, available: true },
  { id: 6, name: "Brenna", email: "primis.in@a.com", address: "P.O. Box 823, 6665 Enim. Road", age: 72, companyId: 3, available: true },
  { id: 7, name: "Aidan", email: "pharetra.Nam.ac@elitNulla.edu", address: "Ap #441-5660 Semper St.", age: 49, companyId: 3, available: true },
  { id: 8, name: "Kellie", email: "erat.Sed.nunc@Nullamvelit.co.uk", address: "623-1135 Mauris Rd.", age: 24, companyId: 3, available: true },
  { id: 9, name: "Charles", email: "porttitor.interdum.Sed@ut.co.uk", address: "888-730 Nunc St.", age: 27, companyId: 1, available: true },
  { id: 10, name: "Hasad", email: "egestas@ametmassa.com", address: "Ap #921-2040 Nam Avenue", age: 23, companyId: 6, available: true },
  { id: 11, name: "Madeson", email: "sem@elit.net", address: "Ap #280-3260 Eleifend, Av.", age: 38, companyId: 5, available: false },
  { id: 12, name: "Lamar", email: "ligula@justo.net", address: "776-1996 Nisl Av.", age: 60, companyId: 8, available: true },
  { id: 13, name: "Fallon", email: "ultrices.sit.amet@ami.net", address: "7305 In St.", age: 56, companyId: 8, available: false },
  { id: 14, name: "Savannah", email: "consectetuer.adipiscing@temporbibendum.net", address: "P.O. Box 548, 5366 Nec, Ave", age: 35, companyId: 6, available: true },
  { id: 15, name: "Yuli", email: "ipsum@urnajustofaucibus.net", address: "P.O. Box 595, 8986 Dolor Road", age: 44, companyId: 3, available: true },
  { id: 16, name: "Kitra", email: "ante@velitQuisque.net", address: "P.O. Box 438, 4769 Egestas St.", age: 74, companyId: 1, available: false },
  { id: 17, name: "Demetria", email: "sed.pede.nec@Fusce.ca", address: "P.O. Box 673, 1279 Mollis Rd.", age: 20, companyId: 2, available: true },
  { id: 18, name: "Jarrod", email: "nisl.arcu@tristiquealiquet.net", address: "676-3496 Montes, Ave", age: 55, companyId: 6, available: true },
  { id: 19, name: "Arthur", email: "ultrices@lacusEtiambibendum.edu", address: "P.O. Box 425, 7820 Ac Rd.", age: 62, companyId: 3, available: false },
  { id: 20, name: "Kelsey", email: "Aenean@Fuscefermentum.com", address: "444-692 Quisque St.", age: 42, companyId: 3, available: true },
  { id: 21, name: "Kato", email: "ornare.Fusce@sodalespurus.net", address: "P.O. Box 206, 8429 Ligula. St.", age: 47, companyId: 4, available: true },
  { id: 22, name: "Sharon", email: "ligula@mus.net", address: "454-6712 Est Rd.", age: 47, companyId: 6, available: false },
  { id: 23, name: "Amela", email: "molestie@cursuset.net", address: "P.O. Box 665, 5198 Curae; Avenue", age: 61, companyId: 6, available: false },
  { id: 24, name: "Nelle", email: "id.blandit@egestas.ca", address: "358-9877 Curabitur Rd.", age: 74, companyId: 6, available: false },
  { id: 25, name: "Brent", email: "at@leo.net", address: "7915 Sed Street", age: 47, companyId: 1, available: false },
  { id: 26, name: "Imani", email: "et.commodo.at@duiCum.ca", address: "4232 Elit. Street", age: 31, companyId: 3, available: true },
  { id: 27, name: "Shea", email: "vel@molestietellusAenean.net", address: "269-8421 Nunc Ave", age: 49, companyId: 1, available: true },
  { id: 28, name: "Aretha", email: "arcu.Morbi.sit@nibhlacinia.net", address: "425-3166 Dignissim Ave", age: 23, companyId: 7, available: false },
  { id: 29, name: "Hunter", email: "tempor.diam.dictum@volutpatNulla.com", address: "P.O. Box 428, 3044 Quis, St.", age: 46, companyId: 8, available: false },
  { id: 30, name: "Xantha", email: "nisl.arcu.iaculis@nonleoVivamus.com", address: "578-802 Leo Av.", age: 58, companyId: 6, available: true },
  { id: 31, name: "Rama", email: "non.lobortis.quis@Uttincidunt.net", address: "P.O. Box 556, 2445 Dictum. St.", age: 53, companyId: 4, available: false },
  { id: 32, name: "Serina", email: "at.pede.Cras@Fusce.org", address: "882 Arcu. Rd.", age: 24, companyId: 5, available: true },
  { id: 33, name: "Branden", email: "quis.diam@loremsitamet.org", address: "738-3955 Nullam Rd.", age: 52, companyId: 8, available: true },
  { id: 34, name: "Zorita", email: "elementum.lorem@Praesenteu.co.uk", address: "702-8918 Tortor. Av.", age: 18, companyId: 5, available: false },
  { id: 35, name: "Nora", email: "nec.orci.Donec@nuncac.net", address: "P.O. Box 157, 9345 Faucibus Rd.", age: 29, companyId: 6, available: false },
  { id: 36, name: "Tanya", email: "Nulla@hendreritidante.org", address: "5625 Ac, Avenue", age: 68, companyId: 3, available: false },
  { id: 37, name: "Bradley", email: "mattis@molestieorcitincidunt.edu", address: "Ap #867-3981 Quis, Street", age: 55, companyId: 2, available: true },
  { id: 38, name: "Elmo", email: "eu@odioPhasellusat.ca", address: "P.O. Box 477, 8772 Integer Street", age: 50, companyId: 7, available: true },
  { id: 39, name: "Tana", email: "vulputate@neceleifendnon.com", address: "P.O. Box 475, 4514 Lectus Road", age: 26, companyId: 2, available: true },
  { id: 40, name: "Chastity", email: "In@ProinultricesDuis.net", address: "P.O. Box 406, 3704 Natoque Ave", age: 51, companyId: 3, available: false },
  { id: 41, name: "Cedric", email: "ut.lacus@enimCurabiturmassa.edu", address: "Ap #427-3398 Sociis Avenue", age: 40, companyId: 1, available: false },
  { id: 42, name: "Isaiah", email: "dolor.nonummy@enimCurabiturmassa.edu", address: "Ap #148-938 Sodales St.", age: 41, companyId: 6, available: false },
  { id: 43, name: "Colton", email: "erat.volutpat@Nullamvelit.co.uk", address: "P.O. Box 522, 7976 Dictum Ave", age: 64, companyId: 1, available: false },
  { id: 44, name: "Jasper", email: "ipsum.dolor.sit@pedePraesent.org", address: "124-742 Nulla. St.", age: 45, companyId: 7, available: true },
  { id: 45, name: "Adele", email: "ante@gravidamaurisut.net", address: "P.O. Box 546, 2230 Orci, Street", age: 69, companyId: 7, available: false },
  { id: 46, name: "Lara", email: "neque@Utsagittislobortis.net", address: "Ap #504-3877 Accumsan Rd.", age: 28, companyId: 8, available: false },
  { id: 47, name: "MacKenzie", email: "sed.pede@arcuacorci.edu", address: "1804 Quis Street", age: 73, companyId: 3, available: false },
  { id: 48, name: "Beverly", email: "ornare@faucibuslectusa.org", address: "4207 Sed St.", age: 40, companyId: 6, available: false },
  { id: 49, name: "Chase", email: "Phasellus.dapibus@Curae.com", address: "P.O. Box 587, 3287 Libero Street", age: 30, companyId: 6, available: false },
  { id: 50, name: "Alexis", email: "neque.vitae.semper@nequeet.org", address: "8551 Justo Rd.", age: 21, companyId: 6, available: true },
  { id: 51, name: "Minerva", email: "Sed.nulla@risusDonec.org", address: "2468 Mauris Avenue", age: 64, companyId: 5, available: true },
  { id: 52, name: "Dora", email: "dictum.cursus.Nunc@Naminterdum.org", address: "766-9031 Vel St.", age: 67, companyId: 4, available: false },
  { id: 53, name: "Allen", email: "aliquam.arcu.Aliquam@convallisincursus.ca", address: "209-7452 Nisi. Rd.", age: 65, companyId: 1, available: false },
  { id: 54, name: "Alice", email: "sed.libero@mieleifendegestas.net", address: "Ap #963-3895 Pellentesque Ave", age: 68, companyId: 1, available: false },
  { id: 55, name: "Wendy", email: "malesuada@eu.edu", address: "552-2812 Est. Rd.", age: 22, companyId: 4, available: false },
  { id: 56, name: "Amal", email: "Mauris.vestibulum.neque@nonenim.com", address: "5338 Nunc Road", age: 41, companyId: 2, available: true },
  { id: 57, name: "Isaac", email: "nec@vellectusCum.com", address: "P.O. Box 820, 2464 Arcu. Rd.", age: 73, companyId: 2, available: false },
  { id: 58, name: "Chadwick", email: "libero.et.tristique@eratVivamusnisi.com", address: "Ap #938-6982 Nibh Ave", age: 57, companyId: 2, available: false },
  { id: 59, name: "Stuart", email: "ut.molestie.in@volutpat.co.uk", address: "667-2376 Vel Street", age: 35, companyId: 1, available: true },
  { id: 60, name: "Nora", email: "Sed.diam.lorem@orciUt.net", address: "293-1410 Enim, Rd.", age: 53, companyId: 8, available: true },
  { id: 61, name: "Hiram", email: "est.tempor@DonectinciduntDonec.ca", address: "126-5324 Id Street", age: 37, companyId: 8, available: false },
  { id: 62, name: "Virginia", email: "sociis@purusNullamscelerisque.edu", address: "P.O. Box 752, 6606 Non, Av.", age: 20, companyId: 2, available: true },
  { id: 63, name: "Hedwig", email: "ipsum@Cum.co.uk", address: "P.O. Box 661, 3904 Sit Rd.", age: 52, companyId: 6, available: false },
  { id: 64, name: "Dane", email: "fringilla.porttitor@liberoProinmi.edu", address: "9689 Urna Av.", age: 62, companyId: 6, available: true },
  { id: 65, name: "Jessica", email: "Vivamus.nibh@tempusscelerisque.org", address: "569-3134 Orci, Street", age: 21, companyId: 4, available: false },
  { id: 66, name: "Xantha", email: "cursus@faucibus.edu", address: "1963 Porttitor Road", age: 19, companyId: 3, available: false },
  { id: 67, name: "Gil", email: "lorem.luctus.ut@iaculis.ca", address: "Ap #716-4783 Et, Rd.", age: 66, companyId: 8, available: true },
  { id: 68, name: "Bert", email: "cursus.et@lobortismauris.org", address: "Ap #761-4260 Posuere St.", age: 29, companyId: 3, available: false },
  { id: 69, name: "Seth", email: "Fusce.mi@auctorvitaealiquet.org", address: "P.O. Box 630, 1598 Eu, St.", age: 53, companyId: 5, available: true },
  { id: 70, name: "Brandon", email: "Sed.congue.elit@blanditcongue.ca", address: "331-7035 Lectus Street", age: 73, companyId: 4, available: false },
  { id: 71, name: "Madaline", email: "mi.enim.condimentum@Sednullaante.edu", address: "1351 Leo. Rd.", age: 60, companyId: 3, available: true },
  { id: 72, name: "Abbot", email: "mi.eleifend.egestas@Etiamimperdiet.edu", address: "Ap #948-3027 Magna. St.", age: 21, companyId: 7, available: true },
  { id: 73, name: "Eagan", email: "lacus.Quisque@orcisem.net", address: "P.O. Box 251, 1547 Non Av.", age: 35, companyId: 2, available: false },
  { id: 74, name: "Blair", email: "lacus@odioEtiamligula.com", address: "428-1243 Proin Avenue", age: 43, companyId: 2, available: true },
  { id: 75, name: "Jolie", email: "condimentum@pharetraNamac.edu", address: "933-4235 Lobortis Road", age: 29, companyId: 7, available: true },
  { id: 76, name: "Alana", email: "mi@posuereatvelit.edu", address: "Ap #492-4575 Morbi Road", age: 75, companyId: 5, available: true },
  { id: 77, name: "Guy", email: "et.libero.Proin@Seddiam.net", address: "6855 Blandit. Ave", age: 63, companyId: 2, available: true },
  { id: 78, name: "Otto", email: "in.tempus.eu@eratvitaerisus.net", address: "Ap #279-5176 Cras Road", age: 31, companyId: 2, available: false },
  { id: 79, name: "Hiram", email: "neque.non@ridiculusmusDonec.co.uk", address: "P.O. Box 798, 1208 Odio. Rd.", age: 40, companyId: 1, available: true },
  { id: 80, name: "Ocean", email: "sapien.molestie.orci@afeugiattellus.ca", address: "Ap #530-9478 Parturient Av.", age: 57, companyId: 2, available: true },
  { id: 81, name: "Martena", email: "blandit.Nam@Donecfelis.co.uk", address: "398-9305 Varius St.", age: 19, companyId: 8, available: true },
  { id: 82, name: "Jordan", email: "Quisque@purusmaurisa.co.uk", address: "P.O. Box 708, 9309 Nisl. Rd.", age: 74, companyId: 2, available: true },
  { id: 83, name: "Madeline", email: "Morbi.quis@luctusut.com", address: "7770 Tellus Avenue", age: 42, companyId: 8, available: true },
  { id: 84, name: "Victoria", email: "tellus@NullafacilisiSed.net", address: "999-6005 Aliquam Ave", age: 75, companyId: 8, available: true },
  { id: 85, name: "Hadassah", email: "Curae@Donec.com", address: "Ap #593-9344 Massa Av.", age: 73, companyId: 6, available: false },
  { id: 86, name: "Eve", email: "Mauris.blandit.enim@consequatnecmollis.ca", address: "P.O. Box 664, 9422 Dapibus St.", age: 61, companyId: 1, available: true },
  { id: 87, name: "Regina", email: "id.erat@vehiculaetrutrum.org", address: "Ap #369-3294 Eu St.", age: 43, companyId: 5, available: false },
  { id: 88, name: "Hammett", email: "Suspendisse@nequevenenatislacus.ca", address: "P.O. Box 593, 7563 Lobortis Ave", age: 33, companyId: 2, available: true },
  { id: 89, name: "Charity", email: "Maecenas.mi.felis@consequatauctor.com", address: "P.O. Box 962, 1621 Imperdiet Rd.", age: 72, companyId: 6, available: false },
  { id: 90, name: "Baxter", email: "tristique.neque@risus.org", address: "2707 A, Ave", age: 32, companyId: 2, available: false },
  { id: 91, name: "Ignatius", email: "malesuada@sedturpis.net", address: "6717 At St.", age: 19, companyId: 6, available: true },
  { id: 92, name: "Rahim", email: "facilisis@felis.edu", address: "447-1901 Aliquam, Road", age: 74, companyId: 8, available: true },
  { id: 93, name: "Dexter", email: "condimentum.Donec@malesuadavel.net", address: "6995 Malesuada Avenue", age: 50, companyId: 4, available: false },
  { id: 94, name: "Kristen", email: "commodo@penatibusetmagnis.org", address: "962-7336 Amet St.", age: 45, companyId: 3, available: false },
  { id: 95, name: "Marvin", email: "id@aarcuSed.net", address: "8361 Donec St.", age: 28, companyId: 2, available: false },
  { id: 96, name: "Ila", email: "aliquam.eu.accumsan@lacusUt.ca", address: "P.O. Box 757, 8514 Quis Avenue", age: 66, companyId: 2, available: true },
  { id: 97, name: "Cherokee", email: "ridiculus@libero.co.uk", address: "905-3072 Diam Ave", age: 69, companyId: 2, available: false },
  { id: 98, name: "Shelby", email: "Etiam.laoreet.libero@sit.co.uk", address: "9352 Eleifend Rd.", age: 60, companyId: 6, available: false },
  { id: 99, name: "Kennedy", email: "malesuada.fringilla.est@elita.edu", address: "Ap #879-5201 Donec Ave", age: 23, companyId: 7, available: false },
  { id: 100, name: "Travis", email: "vel@magnatellusfaucibus.org", address: "940-3052 Ut St.", age: 64, companyId: 1, available: false }
];


let companies = [
  { id: 1, name: "Google", address: "Ap #904-5154 Urna St.", phone: "(028) 2744 2179", country: "Norway", hiring: false, level: 7 },
  { id: 2, name: "Altavista", address: "768-3119 A Ave", phone: "(013944) 68367", country: "Malawi", hiring: false, level: 3 },
  { id: 3, name: "LucasArts", address: "P.O. Box 368, 2404 Augue Av.", phone: "070 9514 0298", country: "Niue", hiring: false, level: 6 },
  { id: 4, name: "Apple", address: "Ap #240-290 Ridiculus St.", phone: "0800 465 1737", country: "Tokelau", hiring: true, level: 8 },
  { id: 5, name: "Lycos", address: "P.O. Box 163, 2012 Luctus Ave", phone: "(0119) 624 2415", country: "Niue", hiring: true, level: 6 },
  { id: 6, name: "Microsoft", address: "P.O. Box 971, 1507 Donec Av.", phone: "(016977) 3233", country: "Mongolia", hiring: true, level: 6 },
  { id: 7, name: "Yahoo", address: "Ap #253-4142 Ultrices Ave", phone: "(016977) 8990", country: "Nauru", hiring: true, level: 9 },
  { id: 8, name: "Adobe", address: "Ap #827-3345 Purus Ave", phone: "(0111) 073 5249", country: "Egypt", hiring: false, level: 8 },
];

module.exports = { candidates, companies }